### ISSUE TITLE
Auto-deboxing for Real, Int, Bool

### ISSUE THREAD

**Issue by alexandrebouchard** [UBC-Stat-ML/blangDSL#39]
Having to include `[..]` and `.doubleValue` is distracting

**Comment by cubranic** [comment]
It looks like the following two steps will do it:

1. provide a custom synonym types provider, announcing the type synonyms for RealVar, etc. ([example](https://github.com/diverse-project/melange/blob/master/plugins/fr.inria.diverse.melange/src/main/java/fr/inria/diverse/melange/typesystem/MelangeSynonymTypesProvider.xtend))
  
  In the runtime module, include a `bindSynonymTypesProvider ` method:
```java
	def Class<? extends SynonymTypesProvider> bindSynonymTypesProvider() {
		return typeof(fr.inria.diverse.melange.typesystem.MelangeSynonymTypesProvider)
	}
```
2. provide a custom XBase compiler. In its `internalToConvertedExpression()` check the expected type and the actual type, and insert the #toX calls into the generated code. ([example](https://github.com/diverse-project/melange/blob/master/plugins/fr.inria.diverse.melange/src/main/java/fr/inria/diverse/melange/compiler/ModelOrientedXbaseCompiler.xtend))

  In the runtime module, include a `bindXbaseCompiler` method:
```java
	def Class<? extends XbaseCompiler> bindXbaseCompiler() {
		return typeof(fr.inria.diverse.melange.compiler.ModelOrientedXbaseCompiler)
	}
```
